### 
//READ
GET http://localhost:8765/hospitalDetails/get
###
GET http://localhost:8765/hospitalDetails/get/status/Fever
###
GET http://localhost:8765/hospitalDetails/get/diabetes/treatment
###
GET http://localhost:8765/hospitalDetails/get/Fever/treatment(covid)
###
//Age Filtering
GET http://localhost:8765/hospitalDetails/get/age/gt/40

###
///Create
POST http://localhost:8765/hospitalDetails/post
Content-Type: application/json

{
    "patientID": 20,
    "patientName": "Tushar",
    "patientAge": 38,
    "patientBloodGroup": "AB+",
    "patientAddress": "Dindigul",
    "patientContact": 7654901234,
    "patientIssue": "Liver Disease",
    "patientStatus": "Admitted"
}
 
###
//DELETE
DELETE http://localhost:8765/hospitalDetails/delete/mohan
###

DELETE http://localhost:8765/hospitalDetails/delete/Basker
###

//UPDATA
PUT http://localhost:8765/hospitalDetails/change/Fever/treatment(covid)
###
PUT http://localhost:8765/hospitalDetails/updata/Fever/Covid
###